services:
  app:
    build: .
    container_name: cl-app
    ports: 
      - "5000:80"
    depends_on:
      redis:
        condition: service_healthy
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://+:80
    networks:
      - cl-network
    restart: unless-stopped
  
  redis:
    image: redis:alpine
    container_name: cl-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - cl-network

networks:
  cl-network:
    driver: bridge